# This file is part of project link.developers/ld-node-facial-landmark-detector-2.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers.beta/ld-node-facial-landmark-detector-2.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-facial-landmark-detector-2"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

build:
  number: 0
  detect_binary_files_with_perfix: true
  features:
    - {{ COMPILER_FEATURE }}
    - cuda
  skip: 
    true # [aarch64]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ld-cmake-tools
    - ld-data-protobuf
    - flatc
    - tensorflow_cc

  host:
    - link2-cpp
    - opencv
    - ld-lib-image
    - ld-interface-i2d
    - cuda=9.0
    - cudnn

  run:
    - link2
    - opencv
    - ld-lib-image
    - ld-interface-i2d
    - ld-data-protobuf
    - cuda=9.0
    - cudnn
    - tensorflow_cc

test:
  commands:
    - "ld-node-facial-landmark-detector-2 --help"

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers.beta/ld-node-facial-landmark-detector-2"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "A link2 node that recognizes human facial features in images of faces."
