# This file is part of project link.developers/ld-node-facial-landmark-detector-2.
# It is copyrighted by the contributors recorded in the version control history of the file,
# available from its original location https://gitlab.com/link.developers.beta/ld-node-facial-landmark-detector-2.
#
# SPDX-License-Identifier: MPL-2.0

package:
  name: "ld-node-facial-landmark-detector-2"
  version: {{ BUILD_VERSION }}

source:
  git_url: ../

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ld-cmake-tools
    - flatc

  host:
    - link2-cpp

  run:
    - link2

test:
  commands:
    - "ld-node-facial-landmark-detector-2 --help"

extra:
  git-commit: {{ GIT_FULL_HASH }}

about:
  home: "https://gitlab.com/link.developers.beta/ld-node-facial-landmark-detector-2"
  license: "MPL-2.0"
  license_file: "LICENSE"
  summary: "A link2 node that recognizes human facial features in images of faces."
